backend = "glx";

# vertical synchronization to prevent screen tearing
vsync = true;

# Disable partial redraws. fix for GTK flickering.
use-damage = false;

# keep compositing active on full-screen windows
unredir-if-possible = false;

# Disable fading animations
fading = false;
